# -*- coding: utf-8 -*-
"""ShadowFox_Beginner[Boston House Price Prediction].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fbo4awBVU2XBs32h410a_dD7Em6q02Zx
"""

# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Load the dataset
df = pd.read_csv("HousingData.csv")
print(df.head())

# Step 2: Interpretation
df.info()

# Step 2: Check for missing values
df.isnull().sum()

# Step 2.1: Handling missing values by replacing them with the corresponding mean
df = df.fillna(df.mean())


# Checking if the values are handled
df.isnull().sum()

# Step 3: Outlier detection and removal using IQR method
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df.clip(lower=lower_bound, upper=upper_bound, axis=1)

# Step 4: Plotting Correlation Heatmap
import seaborn as sns

# Compute correlation matrix
corr = df.corr()

# Plot heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap of Housing Dataset")
plt.show()

# Step 5: Separate features and target
X = df.drop("MEDV", axis=1)
y = df["MEDV"]

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Step 8: Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 9: Make predictions
y_pred = model.predict(X_test)

# Step 10: Model evaluation
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

# Step 11: Actual vs Predicted plot
plt.figure(figsize=(6, 6))
plt.scatter(y_test, y_pred)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()])
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()